### ISSUE TITLE
Add docs about recursionlimit

### ISSUE THREAD

**Issue by jan25** [messersm/sudokutools#1]
If i added sudokutools as a import in my .py script, and the script breaks with recursion limit reached exception. Please update docs or README about appropriate recursionlimit to set in depending scripts or modules.

EDIT: I'm trying to run mainly this to see the exception `sudokutools.generate.generate(min_key=17, size=(9, 9))`

Thanks for this library!

**Comment by messersm** [comment]
Hi @jan25. Thank you for using sudokutools. :)

Just to make sure, that this is what you want to do: Do you want to create a Sudoku with 81 x 81 cells?

``size`` specifies the ``region_width`` and ``region_height``. So a standard Sudoku requires ``size=(3, 3)`` (which is the default).

(It may be a good idea to rename this parameter, to make it clearer, that this is not the actual size of the sudoku - the whole library works with this name - so if you have a good name, please do tell. :) )

It seems standard Python recursion limit is set to 1000 (on my system at least), which would be enough for Sudokus of (real) size 30 x 30 sudoku, e.g. ``size=(3, 10)`` (31 x 31 would work too, but those don't exist), that's why I'm not sure, if I want to document this (but I'll look into common practise of documenting recursive functions in Python and get back to this).

**Comment by jan25** [comment]
Sorry, I may have misread the docs about `size`. I assumed its the outer grid size. Without this param the stack seems to fit in default recursion limit.

I think it is a good idea to clarify about params in the docs. Maybe call it `region_size=(3,3)` or have a way to provide outer grid size.

**Comment by messersm** [comment]
Yeah, the problem with providing an actual size parameter for was, that there has to be lots of checking going on, because the size can be ambiguous: A 8x8 Sudoku can have boxes of 2x4 or 4x2. Worse: a 12x12 sudoku could have 1x12, 2x6, 3x4, ... boxes. That's why I deliberately didn't provide this option.

I will rename size to box_size. I think, this will be fine for now.

Thank you for the input. :)

**Comment by messersm** [comment]
All done - closing.
